### PR TITLE
fix: SQS crashing error with no active transaction

### LINKED ISSUE #2113: SQS instrumentation can cause Errors
**Describe the bug**

When a transaction is not set and and `sqs.sendMessage` is called an error is thrown:
`Cannot read property 'setDestinationContext' of null`

This was introduced in the SQS instrumentation added in version 3.14.0.

The problem is that `span` can be null here but there is no check for that case - https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/modules/aws-sdk/sqs.js#L154-L156

image

**Expected behavior**

No error, should be handled gracefully.

**Environment (please complete the following information)**

- OS: Linux
- Node.js version: 16.3.0
- Agent version: 3.15.0 (present in 3.14.0 upwards)

**How are you starting the agent? (please tick one of the boxes)**

- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
  serviceName: 'servicename',
  secretToken: 'mysecret',
  serverUrl: 'https://myserver',
  active: true
    ```
  </details>

### PR DESCRIPTION
**Pull request by astorm**
Fixes #2113

This PR modifies adds an additional guard clause to the SQS instrumentation that checks to see if a span was actually started or not.  It also removed the old `currentTransaction` guard clause from `shouldIgnoreRequest` and modifies the unit test accordingly. 

### Checklist

- [x] Implement code
- [x] Add tests
- [x] Add CHANGELOG.asciidoc entry

### CODE REVIEW

File: lib/instrumentation/modules/aws-sdk/sqs.js [hunk 1]
```diff
@@ -130,7 +130,7 @@ function shouldIgnoreRequest (request, agent) {
     }
   }
 
-  if (!agent.currentTransaction) {
+  if (!agent.currentTransaction || agent.currentTransaction.ended) {
```
Comment (trentm) [inline lib/instrumentation/modules/aws-sdk/sqs.js:133]: @astorm What about something like this instead:

```
--- a/lib/instrumentation/modules/aws-sdk/sqs.js
+++ b/lib/instrumentation/modules/aws-sdk/sqs.js
@@ -152,6 +152,10 @@ function instrumentationSqs (orig, origArguments, request, AWS, agent, { version
   const action = getActionFromRequest(request)
   const name = getSpanNameFromRequest(request)
   const span = agent.startSpan(name, type, subtype, action)
+  if (!span) {
+    return orig.apply(request, origArguments)
+  }
+
   span.setDestinationContext(getMessageDestinationContextFromRequest(request))
   span.setMessageContext(getMessageContextFromRequest(request))
```

This is the typical technique I see in the other instrumentations, e.g.:

```
tedious.js
72:        const span = agent.startSpan(null, 'db', 'mssql', 'query')
73-        if (!span) {
74-          return super.makeRequest(...arguments)
75-        }

cassandra-driver.js
45:      const span = agent.startSpan('Cassandra: Connect', 'db', 'cassandra', 'connect')
46-      if (!span) {
47-        return original.apply(this, arguments)
48-      }

mongodb.js
44:    const span = agent.startSpan(name, 'db', 'mongodb', 'query')
45-    if (span) {
46-      activeSpans.set(event.requestId, span)
```

That allows keeping the logic for whether a span could be created inside `agent.startSpan()` instead of duplicating that logic.

**Review by trentm — CHANGES_REQUESTED** [review]

File: CHANGELOG.asciidoc [hunk 2]
```diff
@@ -45,6 +45,8 @@ Notes:
   respectively. As well, <<span-action, `span.action`>> will now be the HTTP
   method (e.g. "GET", "PUT", "POST"), rather than "http". ({pull}2075[#2075])
 
+* Fixed error where SQS messages sent without an active transactions could
+  crash the agent.
```
Comment (trentm) [inline CHANGELOG.asciidoc:49]: Nit: can we link to the issue number?

**Review by trentm — DISMISSED** [review]
One nit.

Assuming tests pass, LGTM.

**Comment by astorm** [comment]
jenkins run the tests please

File: CHANGELOG.asciidoc (hunk 2 above)
Comment (astorm) [reply CHANGELOG.asciidoc]: 👍

File: lib/instrumentation/modules/aws-sdk/sqs.js (hunk 1 above)
Comment (astorm) [reply lib/instrumentation/modules/aws-sdk/sqs.js]: _nod_ -- change made.  We're now checking to see if a span is successfully created after calling startSpan, and if not bailing out by calling the original method.  also, dings the "something to consider for a custom linting rule at a future date" bell 🛎️ .

Comment (trentm) [reply lib/instrumentation/modules/aws-sdk/sqs.js]: >  also, dings the "something to consider for a custom linting rule at a future date" bell 🛎️ .

We could re-implement the agent in Rust which would require us to handle the `Option<Span>`. ;)

**Review by trentm — APPROVED** [review]
