### PR TITLE
fix: add currentTraceIds to typings

### LINKED ISSUE #1630: Property 'currentTraceIds' does not exist on type 'Agent'
**Describe the bug**
Type definitions are not correct. Property exists and works but typescript screams.

**To Reproduce**
Use TypeScript and the following code:
``` ts
import apm from 'elastic-apm-node';
console.log(apm.currentTraceIds);
```

Property 'currentTraceIds' does not exist on type 'Agent'.ts(2339)

**Environment (please complete the following information)**

- OS: [e.g. Linux]: Windows
- Node.js version: 12 latest minor
- Agent version: 3.3.0

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [X] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    basic auth options
    ```
  </details>
- `package.json` dependencies:
  <details>
    <summary>Click to expand</summary>

    ```
        "elastic-apm-node": "^3.3.0",
    ```
  </details>

### PR DESCRIPTION
**Pull request by jahtalab**
This PR adds `agent.currentTraceIds` to typings.

Fixes #1630

### Checklist

- [x] Implement code
- [x] Add tests
- [x] Update TypeScript typings
- [ ] ~~Update documentation~~
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by jahtalab** [comment]
@watson , that's correct, the last commit on the PR is not mine. There's seems to have been a force-push to master which probably caused this problem.

**Comment by watson** [comment]
Ah yes, that force push was me. There was a problem with a commit that was merged into master so I had to force push it to fix tests - sorry about that 😓

File: test/types/index.ts [hunk 1]
```diff
@@ -15,6 +15,10 @@ const span = agent.currentSpan
 if (span) span.end()
 const traceparent = agent.currentTraceparent
 if (traceparent) traceparent.split('-')
+const currentTraceIds = agent.currentTraceIds
+let traceId = currentTraceIds['trace.id'] || ''
+traceId += '-' + typeof currentTraceIds['transaction.id'] !== 'undefined' ? 
+  currentTraceIds['transaction.id'] : currentTraceIds['span.id']
```
Comment (watson) [inline test/types/index.ts:21]: The tiniest of nits - just aligning with how things have previously been structured elsewhere in the repo.

```suggestion
traceId += '-' + currentTraceIds['transaction.id'] === undefined
  ? currentTraceIds['transaction.id']
  : currentTraceIds['span.id']
```

**Comment by watson** [comment]
The Windows error you see on Jenkins is unrelated and is fixed in master. It's just an issue with Docker on Jenkins. I'll merge in `master` just to see that everything passes.

File: test/types/index.ts [hunk 2]
```diff
@@ -15,6 +15,11 @@ const span = agent.currentSpan
 if (span) span.end()
 const traceparent = agent.currentTraceparent
 if (traceparent) traceparent.split('-')
+const currentTraceIds = agent.currentTraceIds
+let traceId = currentTraceIds['trace.id'] || ''
+traceId += '-' + currentTraceIds['transaction.id'] === undefined
+  ? currentTraceIds['transaction.id']
+  : currentTraceIds['span.id']
```
Comment (watson) [inline test/types/index.ts:22]: I didn't catch this issue before, but as far as I see this statement will always be `false` because there's implicit parentheses around `('-' + currentTraceIds['transaction.id'])` 🤔 I might read the code wrong, but I think what you meant was something like this right?

```suggestion
traceId += '-' + (currentTraceIds['transaction.id'] === undefined
  ? currentTraceIds['transaction.id']
  : currentTraceIds['span.id'])
```

Though I'm not sure it matters much since this is the TypeScript tests, so we don't really care about the result 😅

Comment (jahtalab) [reply test/types/index.ts:22]: Good catch 👍

though as long as it compiles we should be fine 😄

**Comment by paulrostorp** [comment]
Any visibility on when this will be released ?
