### PR TITLE
Fixes #4508: Ensure `return` in binding definitions is not null or…

### LINKED ISSUE #4508: Azure Functions v4 - Service Bus functions throw TypeError: Cannot read properties of undefined (reading 'direction')
**Describe the bug**

The error ` TypeError: Cannot read properties of undefined (reading 'direction')` is thrown when a azure function(v4) is triggered to consume a service bus topic message.

**To Reproduce**

See [this git repo](https://github.com/wladimirguerra/elastic-apm-az4-bug) for a reproducible code.

**Expected behavior**

The error should not happen and the function should run.

**Environment (please complete the following information)**

- OS: OSX and Azure Functions and Ubuntu
- Node.js version: v20.18.1
- APM Server version: the server is never reached. The error is thrown before an attempt to connect
- Agent version: 4.11.1

**How are you starting the agent? (please tick one of the boxes)**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ X] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

**Additional context**

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```
    "@azure/functions": "4.7.0",
    "elastic-apm-node": "4.11.1"
```
</details>

### PR DESCRIPTION
**Pull request by wladimirguerra**
Fixes #4508 

Ensure `return` in binding definitions is not null or undefined.

Previously, `context?.options?.return` was added to `bindingDefinitions` without checking its presence. This change adds a conditional check to verify its existence before pushing.

### Checklist

- [x] Implement code
- [ ] Add tests
- [ ] Update TypeScript typings
- [ ] Update documentation
- [ ] Add CHANGELOG.asciidoc entry
- [x] Commit message follows [commit guidelines](https://github.com/elastic/apm-agent-nodejs/blob/main/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by wladimirguerra** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [55c4799](https://github.com/elastic/apm-agent-nodejs/commit/55c47998f2e359d368ea4692b8eec79ce97aa981)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Done!

File: lib/instrumentation/azure-functions.js [hunk 1]
```diff
@@ -376,7 +376,9 @@ function instrument(agent) {
         direction: context?.options?.trigger?.direction,
       });
       // Output bindings
-      bindingDefinitions.push(context?.options?.return);
+      if(context?.options?.return) {
```
Comment (trentm) [inline lib/instrumentation/azure-functions.js:379]:
```suggestion
      if (context?.options?.return) {
```

lint fix. I tried to push this fix to your branch, but that failed on permissions:

```
% git push wladimirguerra HEAD
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 11 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 652 bytes | 163.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:wladimirguerra/apm-agent-nodejs.git
 ! [remote rejected]   HEAD -> wladimirguerra/main (permission denied)
error: failed to push some refs to 'github.com:wladimirguerra/apm-agent-nodejs.git'
```

Not sure why. Perhaps because it is on your "main" branch, or could be I'm just messing up the git-fu.

**Review by trentm — APPROVED** [review]
Thanks very much for the repro and the fix!
I'll merge once tests pass.

**Comment by trentm** [comment]
@colleenmcginnis Sorry to bug you again. Is the docs-build-pr check here possibly stuck?
I'd like to learn how to dig into this, if helpful, but I understand this docs build will be short lived.

**Comment by colleenmcginnis** [comment]
run docs-build

**Review by trentm — APPROVED** [review]

**Review by david-luna — APPROVED** [review]
