### PR TITLE
test: fix flaky `disableInstrumentations` tests

### LINKED ISSUE #535: Fix flaky `disableInstrumentations` test
The tests for `disableInstrumentations` are flaky. The often fail with the following error (here captured on AppVeyor, but the error occurs on Travis and Jenkins as well):

```
# multiple modules by csv string -> bluebird,elasticsearch,express-graphql,generic-pool,handlebars,http,http2,knex,mimic-response,mysql,pg,restify,ws
ok 140 disabled all selected modules
(node:3872) ExperimentalWarning: The http2 module is an experimental API.
C:\projects\apm-agent-nodejs\lib\request.js:70
  payload = agent._filters.process(payload)
                           ^
TypeError: agent._filters.process is not a function
    at Object.sendTransactions [as transactions] (C:\projects\apm-agent-nodejs\lib\request.js:70:28)
    at C:\projects\apm-agent-nodejs\lib\instrumentation\index.js:68:17
    at value.get.value (C:\projects\apm-agent-nodejs\node_modules\async-value-promise\index.js:30:27)
    at AsyncValue.get (C:\projects\apm-agent-nodejs\node_modules\async-value\index.js:17:7)
    at AsyncValuePromise.then (C:\projects\apm-agent-nodejs\node_modules\async-value-promise\index.js:29:20)
    at Queue.onFlush [as _onFlush] (C:\projects\apm-agent-nodejs\lib\instrumentation\index.js:66:41)
    at Queue.flush (C:\projects\apm-agent-nodejs\lib\queue.js:39:8)
    at Timeout.<anonymous> (C:\projects\apm-agent-nodejs\lib\queue.js:53:10)
    at Timeout.elasticAPMCallbackWrapper [as _onTimeout] (C:\projects\apm-agent-nodejs\lib\instrumentation\index.js:187:27)
    at ontimeout (timers.js:498:11)
    at Timer.unrefdHandle (timers.js:611:5)
C:\projects\apm-agent-nodejs\test\test.js:112
    if (err) throw err
```

### PR DESCRIPTION
**Pull request by watson**
Sometimes the `test/config.js` tests would run long enough for one of the agents created during the tests to flush its queue. The agent had its filters mocked and wasn't expected to actualy send data anywhere, so this would result in an uncaught exception.

This fix does away with mocking of the filters as there was really no reason for it. It also patches the test that wrongly added a transaction to the queue. So now the queue should never be flushed no matter how long the tests run.

Fixes #535

### CODE REVIEW

File: test/config.js [hunk 1]
```diff
@@ -298,9 +298,14 @@ captureBodyTests.forEach(function (captureBodyTest) {
...
     var errors = request.errors
+    var transactions = request.transactions
     request.errors = function (agent, list, cb) {
       request.errors = errors
-      return cb(list, agent)
+      return cb(list)
+    }
+    request.transactions = function (agent, list, cb) {
+      request.transactions = transactions
+      return cb()
```
Comment (Qard) [inline test/config.js]: Out of curiosity, what is this needed for?

Comment (watson) [reply test/config.js]: Faking that the transactions have been sent to the APM Server by calling the callback

Comment (watson) [reply test/config.js]: Maybe nothing in the code base is waiting for this to be called, but better safe than sorry - especially if this expectation changes at a later date

Comment (Qard) [reply test/config.js]: That's fair. 👍
