### PR TITLE
fix(express): don't swallow error handling middleware

### LINKED ISSUE #1007: Unhandled exceptions while using elastic-apm-node
**Describe the bug**
Since I have started using elastic-apm-node, it has started throwing unhandled errors which is causing unnecessary alerts and node process to crash, error is  :
```
SyntaxError: Value expected to be an array/object but is not
     at JSON.parse (<anonymous>)
     at ServerResponse.res.end (/usr/src/app/node_modules/swagger-express-validator/index.js:147:20)
     at write (/usr/src/app/node_modules/finalhandler/index.js:297:9)
     at send (/usr/src/app/node_modules/finalhandler/index.js:301:5)
     at Immediate.<anonymous> (/usr/src/app/node_modules/finalhandler/index.js:133:5)
     at Immediate.<anonymous> (/usr/src/app/node_modules/elastic-apm-node/lib/instrumentation/modules/finalhandler.js:24:20)
     at Immediate.<anonymous> (/usr/src/app/node_modules/express/lib/router/index.js:635:15)
     at Shim.applySegment (/usr/src/app/node_modules/newrelic/lib/shim/shim.js:1387:20)
     at Immediate.wrapper [as _onImmediate] (/usr/src/app/node_modules/newrelic/lib/shim/shim.js:2022:17)
     at runCallback (timers.js:796:20)
     at tryOnImmediate (timers.js:752:5)
     at processImmediate [as _immediateCallback] (timers.js:729:5)
```

**To Reproduce**
1. Use this config 
node : 8.9.0
elastic-apm-node : 2.9.0
apm-server : 6.5.1
```
export ELASTIC_APM_ENABLED=true
export ELASTIC_APM_SERVER_URL="http://elastic-search-apm.urbanclap.infra:8200"
export ELASTIC_APM_SERVICE_NAME="$SERVICE_ID-$ENV"
export ELASTIC_APM_ASYNC_HOOKS=false 
export ELASTIC_APM_CAPTURE_BODY="off"
export ELASTIC_APM_TRANSACTION_SAMPLE_RATE=0.1
export ELASTIC_APM_CAPTURE_EXCEPTIONS=false
export ELASTIC_APM_CAPTURE_ERROR_LOG_STACK_TRACES="never"
export ELASTIC_APM_CAPTURE_SPAN_STACK_TRACES=false
export ELASTIC_APM_SOURCE_LINES_SPAN_APP_FRAMES=0
export ELASTIC_APM_SOURCE_LINES_SPAN_LIBRARY_FRAMES=0
export ELASTIC_APM_SOURCE_LINES_ERROR_APP_FRAMES=0
export ELASTIC_APM_SOURCE_LINES_ERROR_LIBRARY_FRAMES=0
export ELASTIC_APM_ERROR_MESSAGE_MAX_LENGTH="1kb"
export ELASTIC_APM_STACK_TRACE_LIMIT=0
export ELASTIC_APM_TRANSACTION_MAX_SPANS=100
export ELASTIC_APM_API_REQUEST_TIME="10s"
export ELASTIC_APM_API_REQUEST_SIZE="768kb"
export ELASTIC_APM_METRICS_INTERVAL="30s"
```

**Expected behavior**
There should not be any unhandled exceptions thrown from the library to the service using it. 

**Environment (please complete the following information)**
- OS: [ubuntu: 16.04]
- Node.js version:  8.9.0
- APM Server version: 2.9.0
- Agent version: 6.5.1

**How are you starting the agent? (please tick one of the boxes)**
- [x] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [ ] Starting node with `-r elastic-apm-node/start`

### PR DESCRIPTION
**Pull request by watson**
If `captureExceptions` was set to `false` and error was thrown inside of an Express application, any user-provided error handling middleware would not be called.

Fixes elastic/apm-agent-nodejs#1007

### Checklist

- [x] Implement code
- [x] Add tests

### CODE REVIEW

File: lib/instrumentation/modules/express.js [hunk 1]
```diff
@@ -60,9 +61,20 @@ module.exports = function (express, agent, { version, enabled }) {
           }
         } else {
           handle = function (err, req, res, next) {
+            if (!layer.route && layerPath && typeof next === 'function') {
```
Comment (watson) [inline lib/instrumentation/modules/express.js]: This if-block is technically not part of the fix, but I figured that it would be best to patch the `next` function in the error handling layer just as we do in the regular layers.

Comment (watson) [reply lib/instrumentation/modules/express.js]: @Qard after looking more into this, I don't think this is needed in an error handler at all 🤔 I don't think it messes things up, but it just adds overhead

File: .tav.yml [hunk 2]
```diff
@@ -79,7 +79,11 @@ graphql:
   commands: node test/instrumentation/modules/graphql.js
 express:
   versions: '>=4'
-  commands: node test/instrumentation/modules/express/basic.js
+  commands:
+    - node test/instrumentation/modules/express/basic.js
+    - node test/instrumentation/modules/express/error-handdling-1.js
+    - node test/instrumentation/modules/express/error-handdling-2.js
+    - node test/instrumentation/modules/express/set-framework.js
```
Comment (watson) [inline .tav.yml]: Forgot this when I made the set-framework tests previously. Will make a separate PR to update the other framework TAV tests

File: lib/instrumentation/modules/express.js (hunk 1 above)
Comment (Qard) [reply lib/instrumentation/modules/express.js]: Yeah...I feel like there might have been a _reason_ we didn't have that here. 🤔

**Comment by Qard** [comment]
I would maybe indicate the state of `captureExceptions` in the filenames for easier navigation. Also, not sure about the push/pop thing. Other than that, LGTM.

File: lib/instrumentation/modules/express.js (hunk 1 above)
Comment (watson) [reply lib/instrumentation/modules/express.js]: Removing it...
