### PR TITLE
fix: instrument http/https.get requests

### LINKED ISSUE #953: Outgoing http.get requests are not traced
It seems like only `http.request` requests are traced.

Related Discuss topic: https://discuss.elastic.co/t/apm-not-correlating-trace/172758/3

### PR DESCRIPTION
**Pull request by watson**
For `http.get` this was broken in Node.js 8 and up
For `https.get` this was broken in Node.js 9 and up

Fixes #953

### CODE REVIEW

**Comment by watson** [comment]
Tip: The diff for this PR is best viewed while ignoring whitespace:

image

**Comment by watson** [comment]
Hmm yeah. Issue seems to be that we're now capturing some `http.get` spans that we didn't catch before. So we're getting spans we didn't expect

**Comment by watson** [comment]
@Qard It should work now. I'm not proud of the fix though. It would be nice to have a way to make requests that you somehow mark as "not to be traced". But that might be out of scope of this PR?

File: test/instrumentation/modules/http/aborted-requests-enabled.js [hunk 1]
```diff
@@ -420,3 +420,8 @@ function resetAgent (cb) {
   agent._instrumentation.currentTransaction = null
   agent._transport = mockClient(1, cb)
 }
+
+function get () {
+  agent._instrumentation.currentTransaction = null
```
Comment (Qard) [inline test/instrumentation/modules/http/aborted-requests-enabled.js]: How is there a `currentTransaction` set in the first place, when these tests are resetting the agent before each test? 🤔

Comment (watson) [reply test/instrumentation/modules/http/aborted-requests-enabled.js]: It's somehow leaking from the previous test inside the `listen` callback - but only sometimes. I tried to figure out why but couldn't without extensive debugging.

Comment (watson) [reply test/instrumentation/modules/http/aborted-requests-enabled.js]: And funny enough, it's only an issue on Node.js 8.x 🤷‍♂️ So there must be something in regards to how `server.listen` works there.

Comment (Qard) [reply test/instrumentation/modules/http/aborted-requests-enabled.js]: I wonder if that's a bug in how we're using the `patch-async.js` stuff, because it patches the internal `net._listen2` method. 🤔

Comment (watson) [reply test/instrumentation/modules/http/aborted-requests-enabled.js]: I don't think it's related to `patch-async.js` as this also happens when using Async Hooks as far as I ca see

**Comment by watson** [comment]
I agree. Maybe we should make an issue to look into this later
