### PR TITLE
fix(metrics): use noop logger in metrics reporter

### LINKED ISSUE #899: Metrics code can be too chatty
Sometimes the metrics code will log the following to STDOUT (or maybe it's STDERR??):

```
{"name":"Reporter","hostname":"watson.localdomain","pid":33099,"level":50,"msg":"Failed to send metrics to signal fx Error: value is not defined\n    at Object.of (/Users/watson/code/node_modules/elastic-apm-node/node_modules/optional-js/index.js:9:19)\n    at MetricsReporter._reportMetricsWithInterval (/Users/watson/code/node_modules/elastic-apm-node/node_modules/measured-reporting/lib/reporters/Reporter.js:177:16)\n    at Immediate.setImmediate (/Users/watson/code/node_modules/elastic-apm-node/node_modules/measured-reporting/lib/reporters/Reporter.js:143:14)\n    at Immediate.elasticAPMCallbackWrapper [as _onImmediate] (/Users/watson/code/node_modules/elastic-apm-node/lib/instrumentation/index.js:206:27)\n    at processImmediate (timers.js:637:19)","time":"2019-03-05T09:48:49.129Z","v":0}
```

This can easily be reproduced by running `node test/config.js`.

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ fix #899 

- [x] Implement code
- [ ] Add tests
- [ ] Update documentation

### CODE REVIEW

**Comment by Qard** [comment]
Just a note: this doesn't stop bunyan from being installed, so we still need https://github.com/yaorg/node-measured/pull/61 to land before the agent will install properly on Windows.

**Comment by watson** [comment]
I assume this is somewhat related to #899?

**Comment by Qard** [comment]
Yeah, by default measured logs with bunyan. We should probably be using our own logger, though we don’t have control over what level things are logged at in measured and it may not match what we want...

**Comment by watson** [comment]
It's normally an anti-pattern for modules like this to log to stdout/stderr IMO. I'd prefer if it didn't at all. If we can't get this changed, I'm considering if we should fork it

**Comment by Qard** [comment]
I have commit access to it, so we can make changes as-needed. I think the built-in logging makes sense--not with bunyan though...

We can just change the logger to something that matches our expectations. It's easy to give it a logger that logs nothing. I agree that it should _probably_ be silent by default though.

**Comment by watson** [comment]
My bad. I didn't know that the default usage of measured-reporting was to log to stdout. In that case depending on a logger like pino is obviously not an anti-pattern. But it still would be nice if we didn't have to add it to the dependency tree 🤷‍♂️

**Comment by Qard** [comment]
Yeah. I can suggest pulling the log reporter out to another module and having the core module just export an abstract interface to create a concrete implementation on top of. 🤔

**Comment by vigneshshanmugam** [comment]
I do agree that we cannot control the external deps (bunyan in this case). Can we do this instead to prevent it from getting installed? 
```json
"bunyan": "file:../empty-file.js"
``` 

We include this in our `package.json` and let npm link do the magic. This is not a perfect solution, But we can avoid it from getting installed. We used to follow some similar approach by using yarn resolutions https://yarnpkg.com/lang/en/docs/selective-version-resolutions/.

**Comment by watson** [comment]
@vigneshshanmugam I'd prefer if we didn't have to resort to hacks like that.

I'm leaning more and more towards dropping this module as a dependency all together as it sounds like we're actually using it wrong. Instead we should probably just fork it - unless of course we can change the scope of the module to not be focused on logging to STDOUT if the author is ok with it

**Comment by Qard** [comment]
I'm a collaborator on measured, so we shouldn't have any trouble making whatever changes are needed. Just need to decide what they are. I have a PR open at the moment, switching it to use pino here: https://github.com/yaorg/node-measured/pull/61

**Comment by vigneshshanmugam** [comment]
@StephanBenning But I think even switching to pino wont help us with logging it to stdout right? can we pass a custom stream to the logger in the tests and avoid using the `result.stdout` for validation?

**Comment by watson** [comment]
@vigneshshanmugam wrong Stephen ;)

But you're right, switching to pino will not change that it's logging. But it will fix the compliation issue, which is the most pressing one. But you're right that we don't want it to log either. A quick fix could be to pass in a no-op logger as an argument. But the right fix would be to refactor the module to not log to stdout by default at all, and hence not have a dependency either pino or bunyan. @Qard and I just had a discussion about it and that's our end goal

**Comment by vigneshshanmugam** [comment]
Oops, fixed my comment. Sure sounds good to me. Do you want me to make changes in this PR as well for passing a noop logger in tests? Or we wait for the proper fix by not logging to stdout in the other module?

**Comment by watson** [comment]
I'll leave that up to @Qard

**Comment by Qard** [comment]
I would just do the no-op logger thing here, that way this can be fixed parallel to the bunyan install thing rather than blocking on it.

**Comment by vigneshshanmugam** [comment]
Sure will do the changes.

**Comment by Qard** [comment]
Looks like it's still using the agent logger rather than a null logger. Were you going to change that?

**Comment by vigneshshanmugam** [comment]
@Qard Do we need it still? I was thinking disabling metrics would as well disable the logging.

**Comment by Qard** [comment]
I think it would still potentially log when users use it, so we should still get a null logger in there.

**Comment by watson** [comment]
@Qard I think we should just change this PR to use a null-logger instead :)

**Comment by vigneshshanmugam** [comment]
@Qard @watson replaced the logger with noop logger, Please check now.

File: test/_agent.js [hunk 1]
```diff
@@ -8,13 +8,35 @@ var Filters = require('object-filter-sequence')
...
+  info () { return noopFn }
+  fatal () { return noopFn }
+  error () { return noopFn }
+}
+
+class AgentWithNoopLogger extends Agent {
+  constructor () {
+    super()
+    this.defaultLogger = new NoopLogger()
+    Object.defineProperty(this, 'logger', {
```
Comment (vigneshshanmugam) [inline test/_agent.js]: the reason for doing this is because, even if we do `agent._config({ logger: new NoopLogger()} ), It later gets changed in individual tests with original logger which does not  seem to be an ideal behaviour.

**Comment by Qard** [comment]
Oh, actually, we need the MetricsReporter to be given the null logger. This just stops the log output when running the test, but we don't want it for users of the agent either.

**Comment by watson** [comment]
This was just released in v2.7.0
